System:
  name: Mask Detection Application
  NetworkDomains:
    ND3:
      name: Network Domain 3
      AccessDelay: 2.77e-06
      Bandwidth: 10000
      subNetworkDomains:
      - ND1
      - ND2
    ND1:
      name: Network Domain 1
      AccessDelay: 2.77e-06
      Bandwidth: 40000
      subNetworkDomains: []
      ComputationalLayers:
        computationalLayer1:
          name: Edge Layer
          number: 1
          type: PhysicalAlreadyProvisioned
          Resources:
            resource1:
              name: RaspPi_NeuralStick
              totalNodes: 3
              description: Raspberry PIs 4 Model B with Neural stick
              cost: 0.6
              memorySize: 4096
              operatingSystemDistribution: Raspbian
              operatingSystemType: Linux
              operatingSystemVersion: 10
              operatingSystemImageId: None
              secureBoot: string
              measuredBoot: string
              storageSize: 64GB
              storageType: flash
              processors:
                processor1:
                  name: BCM2711
                  type: Cortex-A72
                  architecture: arm64
                  computingUnits: 4
                  internalMemory: 4
                  SGXFlag: false
              accelerators:
                accelerator1:
                  name: Neural stick 2
                  GFLOPS: 100
                  powerDraw: 1
                  memory: 4096
                  processors:
                    processor1:
                      name: P5
                      type: Movidius Myriad X VPU
                      architecture: SHAVE
                      computingUnits: 16
                      internalMemory: 0.256
        computationalLayer2:
          name: Private cloud Layer
          number: 2
          type: PhysicalAlreadyProvisioned
          Resources:
            resource1:
              name: VM1
              totalNodes: 4
              description: Inhouse VM Type 1 UPV
              cost: 0.675
              memorySize: 8192
              storageSize: 25
              storageType: SSD
              operatingSystemDistribution: Ubuntu
              operatingSystemType: Linux
              operatingSystemVersion: 22.04
              operatingSystemImageId: ost://horsemem.i3m.upv.es/c99bc2af-76dd-498f-ba6f-36889db66856XXXX
              secureBoot: false
              measuredBoot: false
              onSpot: false
              processors:
                processor1:
                  name: Xeon
                  type: SkyLake
                  architecture: amd64
                  computingUnits: 4
                  internalMemory: 64
                  SGXFlag: false
  Components:
    component1:
      name: blurry-faces-onnx
      executionLayer: 1
      Containers:
        container1:
          image: registry.gitlab.polimi.it/ai-sprint/blurry-faces-onnx:tag
          memorySize: 2048
          computingUnits: 0.9
          trustedExecution: false
          networkProtection: false
          fileSystemProtection: false
          GPURequirement: false
          selectedExecutionResources: RaspPi_NeuralStick
    component2:
      name: mask-detector-onnx
      executionLayer: 2
      Containers:
        container1:
          image: registry.gitlab.polimi.it/ai-sprint/mask-detector:tag
          memorySize: 4096
          computingUnits: 0.9
          trustedExecution: false
          networkProtection: false
          fileSystemProtection: false
          GPURequirement: false
          selectedExecutionResources: VM1
