run_parameters:
  input_files:
    storage_bucket: "storage"
    filename: "test_charlie.mp4"
    number_of_files: 10
    batch_size: 2
    distribution: "deterministic"
    inter_upload_time: 0
  run:
    campaign_dir: "video-transcriber-10-files"
    run_name: ""
    repetitions: 3
    cooldown_time: 30
    parallelism: [4]
  ml_library:
    interpolation_values: [16, 24]
  other:
    time_correction: 2
    debug: False